---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app1
  namespace: app1
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app1
  targetCPUUtilizationPercentage: 50
